//처음 화면을 출력하는 소스 파일

#include "main.h"

int first_menu()  //첫 화면 출력하는 함수
{
	int x = COLS / 2 - 8;
	int y = LINES / 2 - 7;

	print_star();
	ColorSet(7);
	gotoxy(x, y);
	printf("> 게임 시작");
	gotoxy(x, y+2);
	printf("  도움말");
	gotoxy(x, y+4);
	printf("  점수 보기");
	gotoxy(x, y+6);
	printf("  게임종료");
	ColorSet(7);
	gotoxy(COLS - 21, LINES - 17);
	printf("made by [ 건구스 ]");

	screen();
	emoticon();
	print_letter_in_box1("방향키로 움직인 뒤, 스페이스 바로 메뉴를 선택하세요");

	gotoxy(x, y);

	while (1) {
		int n = keyControl();
		switch (n) {
		case UP: {
			if (y > LINES / 2 - 7) {
				gotoxy(x, y);
				printf(" ");
				y -= 2;
				gotoxy(x, y);
				printf(">");
			}
			break;
		}
		case DOWN: {
			if (y < LINES / 2 - 1) {
				gotoxy(x, y);
				printf(" ");
				y += 2;
				gotoxy(x, y);
				printf(">");
			}
			break;
		}
		case SUBMIT:
			return y - (LINES / 2 - 7);
		}
	}
}

int second_menu()  // 선택 화면 출력하는 함수
{
	int x = COLS / 2 - 6;
	int y = LINES / 2 - 7;

	system("cls");
	print_star();
	gotoxy(x, y);
	printf("> ");
	ColorSet(14);
	printf("쉬움");
	gotoxy(x+2, y+2);
	ColorSet(12);
	printf("보통");
	gotoxy(x+2, y+4);
	ColorSet(192);
	printf("어려움");
	ColorSet(7);
	gotoxy(x+2, y+6);
	printf("다시 메뉴로");

	gotoxy(COLS - 21, LINES - 17);
	printf("made by [ 건구스 ]");

	screen();
	emoticon();
	print_letter_in_box1("방향키로 움직인 뒤, 스페이스 바로 난이도를 선택하세요.");

	gotoxy(x, y);

	while (1) {
		int n = keyControl();
		switch (n) {
		case UP: {
			if (y > LINES / 2 - 7) {
				gotoxy(x, y);
				printf(" ");
				y -= 2;
				gotoxy(x, y);
				printf(">");
			}
			break;
		}
		case DOWN: {
			if (y < LINES / 2 - 1) {
				gotoxy(x, y);
				printf(" ");
				y += 2;
				gotoxy(x, y);
				printf(">");
			}
			break;
		}
		case SUBMIT:
			return y - (LINES / 2 - 7);
		}
	}
}

void main_screen() // 메인 인터페이스 출력
{
	int i, j, x, y;

	x = 6;
	y = 3;
	gotoxy(x, y);
	printf("┌");
	for (i = 0; i < 18; i++) printf("─");
	printf("┐");

	gotoxy(x + 2, y);
	printf("<SCORE>");

	for (j = 0; j < 3; j++) {
		gotoxy(x, y + 1 + j);
		printf("│");
		gotoxy(x + 19, y + 1 + j);
		printf("│");
	}

	gotoxy(x, y + 1 + j);
	printf("└");
	for (i = 0; i < 18; i++) printf("─");
	printf("┘");

	// score창 출력

	x = 90;
	y = 3;
	gotoxy(x, y);
	printf("┌");
	for (i = 0; i < 18; i++) printf("─");
	printf("┐");

	gotoxy(x+2, y);
	printf("<HP>");

	for (j = 0; j < 1; j++) {
		gotoxy(x, y + 1 + j);
		printf("│");
		gotoxy(x + 19, y + 1 + j);
		printf("│");
	}

	gotoxy(x, y + 1 + j);
	printf("└");
	for (i = 0; i < 18; i++) printf("─");
	printf("┘");

	// HP창 출력

	x = 30;
	y = 7;

	gotoxy(x, y);
	printf("┌");
	for (i = 0; i < 53; i++) printf("─");
	printf("┐");

	for (j = 0; j < 18; j++) {
		gotoxy(x, y + 1 + j);
		printf("│");
		gotoxy(x+54, y + 1 + j);
		printf("│");
	}

	gotoxy(x, y + 1 + j);
	printf("└");
	for (i = 0; i < 53; i++) printf("─");
	printf("┘");

	// 건덕이창 출력

	x = 30;
	y = 30;

	gotoxy(x+18, y-1);
	for (i = 0; i < 20; i++) printf("─");

	gotoxy(x, y);
	printf("┌");
	for (i = 0; i < 53; i++) printf("─");
	printf("┐");

	for (j = 0; j < 8; j++) {
		gotoxy(x, y + 1 + j);
		printf("│");
		for (i = 0; i < 53; i++) printf(" ");
		printf("│");
	}

	gotoxy(x, y + 1 + j);
	printf("└");
	for (i = 0; i < 53; i++) printf("─");
	printf("┘");

	// 게임 플레이 대사창 출력

	x = 90;
	y = 13;

	gotoxy(x, y);
	printf("┌");
	for (i = 0; i < 23; i++) printf("─");
	printf("┐");

	for (j = 0; j < 8; j++) {
		gotoxy(x, y + 1 + j);
		printf("│");
		gotoxy(x+24, y + 1 + j);
		printf("│");
	}

	gotoxy(x, y + 1 + j);
	printf("└");
	for (i = 0; i < 23; i++) printf("─");
	printf("┘");

	gotoxy(x + 10, y + 1);
	printf("<TMI>");

	srand(time(0));
	int letter = rand() % 10;
	for (int r = 0; r < 3; r++) {
		tmi(letter, r);
	}

	// 특수 대사창 출력

	x = 47;
	y = 8;

	gotoxy(x, y);
	printf("┌");
	for (i = 0; i < 18; i++) printf("─");
	printf("┐");

	for (j = 0; j < 1; j++) {
		gotoxy(x, y + 1 + j);
		printf("│");
		for (i = 0; i < 18; i++) printf(" ");
		printf("│");
	}

	gotoxy(x, y + 1 + j);
	printf("└──────────────────┘");

	// 말풍선 출력

	gotoxy(37, 37);
	printf("말풍선에 나오는 단어를 정확히 입력하세요!");

	// 도움말 추가
}

void start_game() {

	system("cls");
	main_screen();

	gotoxy(96, 4);
	ColorSet(12);
	printf("■■■■■");

	ColorSet(7);

	print_full();

	gotoxy(32, 37);
	printf("                                              ");
	gotoxy(40, 37);
	printf("[계속하려면 스페이스 바를 누르시오]");

	for (int i = 0; i < 8; i++) {
		story(i);
		char ch = _getch();
		if (ch == 32) {
			main_screen();
			gotoxy(32, 37);
			printf("                                              ");
			gotoxy(40, 37);
			printf("[계속하려면 스페이스 바를 누르시오]");
		}
	}
	gotoxy(32, 37);
	printf("                                              ");
}

void screen() // 대화창 출력하는 함수
{
	int i, j;

	gotoxy(0, LINES - 15);
	printf("┌");
	for (i = 0; i < COLS_BOX; i++) printf("─");
	printf("┐\n");

	for (j = 0; j < LINES_BOX; j++) {
		printf("│");
		for (i = 0; i < COLS_BOX; i++) printf(" ");
		printf("│\n");
	}

	printf("└");
	for (i = 0; i < COLS_BOX; i++) printf("─");
	printf("┘\n");
}

void emoticon() // 첫 화면 이모티콘
{
	ColorSet(10);  // 둠칫 고양이 시작
	gotoxy(84, 12);
	printf("⊂_＼");
	gotoxy(84, 13);
	printf("　 ＼＼ Λ＿Λ");
	gotoxy(84, 14);
	printf("　　 ＼( 'ㅅ' ) 두둠칫");
	gotoxy(84, 15);
	printf("　　　 >　⌒＼");
	gotoxy(84, 16);
	printf("　　　/ ♥ へ＼");
	gotoxy(84, 17);
	printf("　　 /　　/　＼＼");
	gotoxy(84, 18);
	printf("　　 |　ノ　　 ＼_つ");
	gotoxy(84, 19);
	printf("　　/　/두둠칫");
	gotoxy(84, 20);
	printf("　 /　/");
	gotoxy(84, 21);
	printf("　(　(＼");
	gotoxy(84, 22);
	printf("　| |、 ＼");
	gotoxy(84, 23);
	printf("　| | ＼ ⌒)");
	gotoxy(84, 24);
	printf("　| |　　) /");
	gotoxy(84, 25);
	printf(" ノ )　  L|");
	ColorSet(7);  // 둠칫 고양이 종료

	ColorSet(10);  // 타자 이모티콘 시작
	gotoxy(17, 13);
	printf("\a☆□□□□□□☆");  // 소리난다
	gotoxy(17, 14);
	printf("□■■■□■□□");
	gotoxy(17, 15);
	printf("□■□□□■□□");
	gotoxy(17, 16);
	printf("□■■■□■■□");
	gotoxy(17, 17);
	printf("□■□□□■□□");
	gotoxy(17, 18);
	printf("□■■■□■□□");
	gotoxy(17, 19);
	printf("□□□□□□□□");
	gotoxy(17, 20);
	printf("□■■■□■□□");
	gotoxy(17, 21);
	printf("□□■□□■□□");
	gotoxy(17, 22);
	printf("□□■□□■■□");
	gotoxy(17, 23);
	printf("□■□■□■□□");
	gotoxy(17, 24);
	printf("□■□■□■□□");
	gotoxy(17, 25);
	printf("☆□□□□□□☆ game");
    // 타자 임티 종료

	ColorSet(7);
	gotoxy(47, 9);
	printf("=======================");
	gotoxy(51, 10);
	printf("<건덕이 잡기v1>");
	gotoxy(47,11);
	printf("=======================");
}

void print_star()  // 무지개 별 출력
{
	int i;
	int d = 1;
	for (i = 1; i <= COLS; i++) //첫 째줄 별 출력
	{
		printf("*");
		if (d == 15)
			d = d - 13;
		else
			d++;
		ColorSet(d);
	}
	ColorSet(7);
	gotoxy(0, LINES - 16);
	for (i = 1; i <= COLS; i++)
	{
		printf("*");
		if (d == 15)
			d = d - 13;
		else
			d++;
		ColorSet(d);
	}

}
void catchmeifyoucan() // 첫 화면 출력
{
	gotoxy(0, 8);
	printf("                                                    \n");
	printf("                                  \n");
	printf("                   \n");
	printf("                  \n");
	printf("                  \n");
	printf("                     \n\n");
	//
	printf("                                              #   ####  ####  ####  #   ###\n");
	printf("                                              #   #   ##    ##   #  #               \n");
	printf("                                             ##    # #        # #   #     #      \n");
	printf("                                              #     #   #  #   #    #    #     \n");
	printf("                                              #     #          #    #   #    \n");
	printf("                                                     #        #     #     #   \n");
	printf("                                             ##       ##    ##      #     #         \n");
	printf("                                              #         ####        #     #         \n\n");
	//
	printf("         \n");
	printf("               \n");
	printf("         \n");
	printf("         \n");
	printf("             \n");
	printf("             \n");
	printf("                                             \n");
	printf("                                   \n");
	printf("                           \n");
	Sleep(300);

	gotoxy(0, 8);
	printf("                                                     \n");
	printf("                                        \n");
	printf("                   \n");
	printf("                 \n");
	printf("                                    <--(@@@@      _-@@            @@-_      @@@@)-->    \n");
	printf("                                           @@@@@@@                    @@@@@@@              \n\n");
	//
	printf("                                    #######   #   ####  ####  ####  #   ######  #          \n");
	printf("                                    #         #   #   ##    ##   #  #       #   #                \n");
	printf("                                    #    ######    # #        # #   #     ##    ###              \n");
	printf("                                    #         #     #   #  #   #    #    #  #   #             \n");
	printf("                                    #######   #     #          #    #   #    #  #          \n");
	printf("                                                     #        #     #     #     #       \n");
	printf("                                      #########       ##    ##      #     #######              \n");
	printf("                                              #         ####        #     #######           \n\n");
	//
	printf("                                            * C A T C H M E I F Y O U C A N *                     \n");
	printf("                               )                                                        (         \n");
	printf("                                      @@@@@@    _____@@#<<(==)>>#@@_____    @@@@@@        \n");
	printf("         \n");
	printf("              \n");
	printf("                                   \n");
	printf("                                                     \n");
	printf("                                                       \n");
	printf("                                                       \n");
	Sleep(300);

	gotoxy(0, 8);
	printf("                                                     @@          @@\n");
	printf("                                                  (@@              @@)\n");
	printf("                     @@)               @@          @:    (:@@:)    :@          @@               (@@\n");
	printf("                    @                 :#            @@@@@@0@@0@@@@@@            #:                 @\n");
	printf("                   (##@@#:      (#@#<--(@@@@      _-@@            @@-_      @@@@)-->#@#)     :#@@##)\n");
	printf("                        (@@@@@@@@@         @@@@@@@                    @@@@@@@         @@@@@@@@@)\n\n");
	//
	printf("                       #####    #   #######   #   ####  ####  ####  #   ######  #    ########  #      \n");
	printf("                           #    #   #         #   #   ##    ##   #  #       #   #          #   #          \n");
	printf("                          # #####   #    ######    # #        # #   #     ##    ###       #    #         \n");
	printf("                         #      #   #         #     #   #  #   #    #    #  #   #        #     #       \n");
	printf("                        #       #   #######   #     #          #    #   #    #  #       #      #        \n");
	printf("                          #                          #        #     #     #     #      #       #      \n");
	printf("                          #           #########       ##    ##      #     #######     #        #            \n");
	printf("                          #######             #         ####        #     #######    #         #            \n\n");
	//
	printf("            @@)                             * C A T C H M E I F Y O U C A N *                      (@@\n");
	printf("           @     @@         @@@)                                                        (@@@         @@     @\n");
	printf("          @    _@  @       @          @@@@@@    _____@@#<<(==)>>#@@_____    @@@@@@          @       @  @_    @\n");
	printf("          (#@@#@       @@@@:@@@@@@@@@@  || @@@@@  | @ << (-==-) >> @ |  @@@@@ ||  @@@@@@@@@@:@@@@       @#@@#)\n");
	printf("               @@@@@@@@              @@@@@   |  @@@@ --<< (==) >>-- @@@@  |   @@@@@              @@@@@@@@\n");
	printf("                                      @   @###@@@  @@@@_        _@@@@  @@@###@   @\n");
	printf("                                                       @-  ()  -@\n");
	printf("                                                        @------@\n");
	printf("                                                         @@__@@\n");
	Sleep(3500);

	gotoxy(0, 8);
	printf("                                                                                                                  \n");
	printf("                                                                                                                  \n");
	printf("                                                                                                                   \n");
	printf("                                                                                                                      \n");
	printf("                                   #<--(@@@@      _-@@            @@-_      @@@@)-->#                              \n");
	printf("                                           @@@@@@@                    @@@@@@@                                   \n\n");
	//
	printf("                                    #######   #   ####  ####  ####  #   ######  #                                \n");
	printf("                                    #         #   #   ##    ##   #  #       #   #                                   \n");
	printf("                                    #    ######    # #        # #   #     ##    ###                                \n");
	printf("                                    #         #     #   #  #   #    #    #  #   #                                 \n");
	printf("                                    #######   #     #          #    #   #    #  #                                  \n");
	printf("                                                     #        #     #     #     #                                   \n");
	printf("                                      #########       ##    ##      #     #######                                   \n");
	printf("                                              #         ####        #     #######                                \n\n");
	//
	printf("                                            * C A T C H M E I F Y O U C A N *                                      \n");
	printf("                                                                                                                   \n");
	printf("                                      @@@@@@    _____@@#<<(==)>>#@@_____    @@@@@@                                 \n");
	printf("                                              #     #          #    #   #                                          \n");
	printf("                                                                                                                   \n");
	printf("                                                                                                                  \n");
	printf("                                                                                                                   \n");
	printf("                                                                                                                  \n");
	printf("                                                                                                                    \n");
	printf("                                                                                                                     \n");
	Sleep(300);

	gotoxy(0, 8);
	printf("                                                    \n");
	printf("                                  \n");
	printf("                   \n");
	printf("                  \n");
	printf("                  \n");
	printf("                     \n\n");
	//
	printf("                                              #   ####  ####  ####  #   ###\n");
	printf("                                              #   #   ##    ##   #  #               \n");
	printf("                                             ##    # #        # #   #     #      \n");
	printf("                                              #     #   #  #   #    #    #     \n");
	printf("                                              #     #          #    #   #    \n");
	printf("                                                     #        #     #     #   \n");
	printf("                                             ##       ##    ##      #     #         \n");
	printf("                                              #         ####        #     #         \n\n");
	//
	printf("         \n");
	printf("               \n");
	printf("         \n");
	printf("         \n");
	printf("             \n");
	printf("             \n");
	printf("                                             \n");
	printf("                                   \n");
	printf("                           \n");
	Sleep(300);

	gotoxy(0, 8);
	printf("                                                                                                                   \n");
	printf("                                                                                                                   \n");
	printf("                                                                                                                   \n");
	printf("                                                                                                                   \n");
	printf("                                                                                                                    \n");
	printf("                                                                                                                    \n\n");
	//
	printf("                                                  ####  ####  ####                                                  \n");
	printf("                                                  #   ##    ##   #                                                 \n");
	printf("                                                   # #        # #                                                 \n");
	printf("                                                    #   #  #   #                                                  \n");
	printf("                                                    #          #                                                  \n");
	printf("                                                     #        #                                                     \n");
	printf("                                                      ##    ##                                                     \n");
	printf("                                                        ####                                                        \n\n");
	//
	printf("                                                                                                                    \n");
	printf("                                                                                                                    \n");
	printf("                                                                                                                    \n");
	printf("                                                                                                                     \n");
	printf("                                                                                                                    \n");
	printf("                                                                                                                     \n");
	printf("                                                                                                                    \n");
	printf("                                                                                                                   \n");
	printf("                                                                                                                     \n");
}
void print_gameover()
{
	ColorSet(12);  // gameover 문구 출력 시작
	gotoxy(3, 5);
	printf("□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□");
	gotoxy(3, 6);
	printf("□□■■■■□□□□■■□□□■□□□□■□■■■■■■□□■■■■□□■□□□□■□■■■■■■□■■■■■□□");
	gotoxy(3, 7);
	printf("□■□□□□□□□■□□■□□■■□□■■□■□□□□□□■□□□□■□■□□□□■□■□□□□□□■□□□□■□");
	gotoxy(3, 8);
	printf("□■□□■■■□□■■■■□□■□■■□■□■■■■■■□■□□□□■□■□□□□■□■■■■■■□■■■■■□□");
	gotoxy(3, 9);
	printf("□■□□■■□□■□□□□■□■□□□□■□■□□□□□□■□□□□■□□■□□■□□■□□□□□□■□□□□■□");
	gotoxy(3, 10);
	printf("□□■■□■□□■□□□□■□■□□□□■□■■■■■■□□■■■■□□□□■■□□□■■■■■■□■□□□□■□");
	gotoxy(3, 11);
	printf("□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□□");
	ColorSet(10);  // gameover 문구 출력 끝
	gotoxy(COLS / 2 - 20, LINES / 2 - 4);  // 우는 소 출력 시작
	printf("□□□□□□□□□□□□□□□□□□□□□");
	gotoxy(COLS / 2 - 20, LINES / 2 - 3);
	printf("□□□□■□□□□□□□□□□□■□□□□");
	gotoxy(COLS / 2 - 20, LINES / 2 - 2);
	printf("□□□■□■□□■■■■■□□■□■□□□");
	gotoxy(COLS / 2 - 20, LINES / 2 - 1);
	printf("□□□■□□■■□□□□□■■□□■□□□");
	gotoxy(COLS / 2 - 20, LINES / 2);
	printf("□■■□□□□□□□□□□□□□□□■■□");
	gotoxy(COLS / 2 - 20, LINES / 2 + 1);
	printf("■□□□□■□□■□□□■□□■□□□□■");
	gotoxy(COLS / 2 - 20, LINES / 2 + 2);
	printf("□■■□□□■■□□□□□■■□□□■■□");
	gotoxy(COLS / 2 - 20, LINES / 2 + 3);
	printf("□□■□□■□□■□□□■□□■□□■□□");
	gotoxy(COLS / 2 - 20, LINES / 2 + 4);
	printf("□□■□□□□□□□□□□□□□□□■□□");
	gotoxy(COLS / 2 - 20, LINES / 2 + 5);
	printf("□□□■□□□□■□□□■□□□□■□□□");
	gotoxy(COLS / 2 - 20, LINES / 2 + 6);
	printf("□□□□■■□□□□□□□□□■■□□□□");
	gotoxy(COLS / 2 - 20, LINES / 2 + 7);
	printf("□□□□□□■■■■■■■■■□□□□□□");
	gotoxy(COLS / 2 - 20, LINES / 2 + 8);
	printf("□□□□□□□□□□□□□□□□□□□□□");  // 우는 소 출력 끝
	ColorSet(7);
}
void print_full()
{

	gotoxy(66, 11);
	printf("0");

	gotoxy(65, 12);
	printf("ㅇ");

	int x = 41;
	int y = 13;

	gotoxy(x, y);
	printf("  ♡          @@@@@    o      ♡          ");
	gotoxy(x, y + 1);
	printf("           @@       @@                    ");
	gotoxy(x, y + 2);
	printf("          @   @@@@    @                 ");
	gotoxy(x, y + 3);
	printf("         @   @ /＼ @   @           ");
	gotoxy(x, y + 4);
	printf("         @         @@@@@@@@@@@@@          ");
	gotoxy(x, y + 5);
	printf("          @       @             @   ");
	gotoxy(x, y + 6);
	printf("           @       @@@@@@@@@@@@@       ");
	gotoxy(x, y + 7);
	printf("           @      @                   ");
	gotoxy(x, y + 8);
	printf("          @       @                  ");
	gotoxy(x, y + 9);
	printf("         @         @                  ");
	gotoxy(x, y + 10);
	printf("        @           @                ");
	gotoxy(x, y + 11);
	printf("       @             @              ");
	gotoxy(x, y + 12);
	printf("      @               @             ");
}
void print_injured()
{
	int x = 41;
	int y = 13;

	gotoxy(x, y);
	printf("              @@@@@                ");
	gotoxy(x, y+1);
	printf("           @@       @@               ");
	gotoxy(x, y+2);
	printf("          @   @@@@    @          ");
	gotoxy(x, y+3);
	printf("         @   @ __ @   @                ");
	gotoxy(x, y+4);
	printf("         @         @@@@@@@@@@@@@       ");
	gotoxy(x, y+5);
	printf("          @       @             @    ");
	gotoxy(x, y+6);
	printf("           @       @@@@@@@@@@@@@        ");
	gotoxy(x, y+7);
	printf("           @      @               ");
	gotoxy(x, y+8);
	printf("          @       @               ");
	gotoxy(x, y+9);
	printf("         @         @              ");
	gotoxy(x, y+10);
	printf("        @           @               ");
	gotoxy(x, y+11);
	printf("       @             @              ");
	gotoxy(x, y+12);
	printf("      @               @             ");
}
void print_almost_die()
{
	int x = 41;
	int y = 13;

	gotoxy(x, y);
	printf("   @  @       @@@@@          @   @       ");
	gotoxy(x, y+1);
	printf("@          @@       @@    @         @     ");
	gotoxy(x, y+2);
	printf("    @     @   @@@@    @               @    ");
	gotoxy(x, y+3);
	printf("  @      @   @ ㅠ  @   @               @   ");
	gotoxy(x, y+4);
	printf("         @         @@@@@@@@@@@@@       ");
	gotoxy(x, y+5);
	printf("          @       @             @     ");
	gotoxy(x, y+6);
	printf("           @       @@@@@@@@@@@@@       ");
	gotoxy(x, y+7);
	printf("           @      @                 ");
	gotoxy(x, y+8);
	printf("          @       @             ");
	gotoxy(x, y+9);
	printf("         @         @                ");
	gotoxy(x, y+10);
	printf("        @           @                   ");
	gotoxy(x, y+11);
	printf("       @             @               ");
	gotoxy(x, y+12);
	printf("      @               @                ");
}
void ending_credit()
{
	int cols = 0;
	system("cls");
	gotoxy(cols, LINES - 1);
	printf("게임 이름: 건덕이 잡기\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 2);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 3);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 4);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 5);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 6);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 7);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 8);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 9);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 10);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 11);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 12);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 13);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 14);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 15);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 16);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 17);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 18);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 19);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 20);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 21);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 22);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 23);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 24);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 25);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 26);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 27);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 28);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 29);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 30);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 31);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 32);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 33);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 34);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 35);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 36);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 37);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 38);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 39);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 40);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 41);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 42);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 43);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, LINES - 44);
	printf("게임 이름: 건덕이 잡기\n");
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, 0);
	printf("                                                                  \n");
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT); 
	gotoxy(cols, 0);
	printf("made by 건구스\n");
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, 0);
	printf("                                                                  \n");
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT); 
	gotoxy(cols, 0);
	printf("팀장: 이다민\n");
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT); 
	gotoxy(cols, 0);
	printf("                                                                  \n");
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	Sleep(CREDIT);
	gotoxy(cols, 0);
	printf("팀원: 박범식 백진률 송현우\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("플레이 해 주셔서 감사합니다.");
	Sleep(CREDIT);
	gotoxy(cols, 0);
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-메인 코딩-\n");
	printf("                                                                  \n");
	printf("이다민\n");
	printf("박범식\n");
	printf("                                                                  \n");
	printf("-디자인 코딩 겸 밸런스-\n");
	printf("                                                                  \n");
	printf("백진률\n");
	printf("송현우\n");
	printf("                                                                  \n");
	printf("-주인공-\n");
	printf("                                                                  \n");
	printf("건덕이\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("제작 기간:\n");
	printf("2021/04/30~2021/06/09\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-후원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("있으면 좋겠네\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("-응원해 주신 분들-\n");
	printf("                                                                  \n");
	printf("우리 엄마\n");
	printf("우리 아빠\n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("                                                                  \n");
	printf("플레이 해 주셔서 감사합니다.\n");
	printf("                                                                ");
	Sleep(5000);
}